version: '3'

tasks:
  test:
    desc: "Runs unit tests"
    cmd:
      - go test -coverprofile=profile.cov -v ./... --tags "json1"
      - go tool cover -func=profile.cov | grep total | awk '{print $3}' | tee coverage.log
      - rm -fr coverage.log profile.cov

  coverage:
    desc: "Check coverage of code"
    cmds:
      - LOG_LEVEL=error ENV=test SELECTOR=static TRANSPORT=memory BROKER=memory go test -coverprofile=profile.cov -v ./... --tags "json1"
      - go tool cover -html=profile.cov
      - rm -fr coverage.log profile.cov
  
  proto:
    desc: "Generates protobuf gateway files."
    cmds:
      - protoc -I $GOPATH/src -I $GOPATH/src/github.com/googleapis/googleapis -I $GOPATH/src/github.com/grpc-ecosystem/grpc-gateway --go_out $GOPATH/src --go-grpc_out $GOPATH/src $GOPATH/src/github.com/PiotrKowalski/square/proto/*.proto
      - protoc -I $GOPATH/src -I $GOPATH/include -I $GOPATH/src/github.com/googleapis/googleapis -I $GOPATH/src/github.com/grpc-ecosystem/grpc-gateway --grpc-gateway_out $GOPATH/src --grpc-gateway_opt logtostderr=true $GOPATH/src/github.com/PiotrKowalski/square/proto/*.proto

  openapi:
    desc: "Generate documentation for API."
    cmds:
      - protoc -I $GOPATH/src -I $GOPATH/src/github.com/googleapis/googleapis -I $GOPATH/src/github.com/grpc-ecosystem/grpc-gateway --proto_path=$GOPATH/src/github.com/PiotrKowalski/square/proto/ --swagger_out=third_party/OpenAPI/ example.proto